# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

stages:

- stage: Build

  jobs:

    - job: Build

      steps:


      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution:  SampleWebApplication/CodeForAzureDevOps.sln
      
      - task: SonarQubePrepare@5
        inputs:
          SonarQube: 'Sonarqube-Az'
          scannerMode: 'MSBuild'
          projectKey: 'Demo-Steve_Demo-Steve'
          projectName: 'Demo-Steve_Demo-Steve'

      - task: VSBuild@1
        inputs:
          solution: SampleWebApplication/CodeForAzureDevOps.sln
          msbuildArgs: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl="$(Agent.TempDirectory)\WebAppContent\\"'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
        
      - task: SonarQubeAnalyze@5
      - task: SonarQubePublish@5
        inputs:
          pollingTimeoutSec: '300'
      
      
      - task: VSTest@2
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\UnitTestForAzureDevOps.dll
            !**\*TestAdapter.dll
            !**\obj\**
            # **\UnitTestForAzureDevOps\**\**\*TestAdapter.dll
            # **\UnitTestForAzureDevOps\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
          runTestsInIsolation: true
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
        
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'webappartifact'
          publishLocation: 'Container'
      
