# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: 
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

- stage: Build

  jobs:

    - job: Build

      steps:


      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
        
      
      # - task: SonarQubePrepare@5
      #   inputs:
      #     SonarQube: 'sq-updated'
      #     scannerMode: 'MSBuild'
      #     projectKey: 'ct-bootcamp-project'
      #     projectName: 'ct-bootcamp-project'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      # - task: SonarQubeAnalyze@5
      # - task: SonarQubePublish@5
      #   inputs:
      #    pollingTimeoutSec: '300'

      - task: VSTest@2
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\UnitTestForAzureDevOps.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
          runTestsInIsolation: true
          codeCoverageEnabled: true
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
      - task: PublishBuildArtifacts@1
        displayName: "Publish the Website Artifact"
        inputs:
          ArtifactName: sample-site
          PathtoPublish: $(build.artifactStagingDirectory)

- stage: Deploymenttoprod
  dependsOn: [Build]
  condition: succeeded('Build')
  jobs: 
  - deployment: deploymentjob
    pool:
      vmImage: 'windows-latest'

    environment:
      name: Trisha Environment
      resourceType: Virtualmachine
    strategy:
     runOnce:
       deploy: 
          steps:      

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                buildVersionToDownload: 'latest'
                targetPath: '$(build.artifactStagingDirectory)'
              
            - task: IISWebAppManagementOnMachineGroup@0
              inputs:
                IISDeploymentType: 'IISWebsite'
                ActionIISWebsite: 'CreateOrUpdateWebsite'
                WebsiteName: 'default website'
                WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
                WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'

            - task: IISWebAppDeploymentOnMachineGroup@0
              inputs:
                WebSiteName: 'default website'
                Package: '$(build.artifactStagingDirectory)\**\*.zip'
                RemoveAdditionalFilesFlag: true
                ExcludeFilesFromAppDataFlag: true
                TakeAppOfflineFlag: true
                XmlTransformation: true
                XmlVariableSubstitution: true